development:
  host: localhost
  database: staggered_ink_development
  #database: sanderstead_parish_development

test:
  host: localhost
  database: staggered_ink_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
  max_retries_on_connection_failure: 20
  persist_in_safe_mode: true
  skip_version_check: true